# Generated by Django 2.0.5 on 2018-05-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180514_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='songs',
            field=models.FileField(default='songs/no_song.mp3', max_length=100000, upload_to='songs'),
        ),
    ]
