# Generated by Django 2.0.5 on 2018-05-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180514_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='images/no_image.png', null=True, upload_to='images'),
        ),
    ]
