# Generated by Django 2.0.5 on 2018-05-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180514_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songFiles', models.FileField(default='no_song.mp3', upload_to='songs')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFiles',
        ),
    ]
